spec:
  inputs:
    username:
      default: "user99"
      description: "The ID of the user (e.g., user01)"

---
stages:
  - build
  - deploy

variables:
  REGISTRY_URL: "docker.io"
  REGISTRY_USERNAME: "rhapsody008"
  IMAGE_NAME: "sample-webapp"
  # This constructs the base URL for the user-specific repo
  GITOPS_BASE_URL: "gitlab.com/${CI_PROJECT_NAMESPACE}/gitops-$[[ inputs.username ]].git"

# ---------------------------------------------------------------------------
# JOB 1: Build and Push
# ---------------------------------------------------------------------------
build-and-push:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    # Assigning input to a local variable for easier use in shell scripts
    CURRENT_USER: $[[ inputs.username ]]
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u $REGISTRY_USERNAME --password-stdin
  script:
    - export TAG="${CURRENT_USER}-$(echo $CI_COMMIT_SHA | cut -c1-8)"
    - echo "Building image for ${CURRENT_USER}..."
    - docker build -t $REGISTRY_URL/$REGISTRY_USERNAME/$IMAGE_NAME:$TAG .
    - echo "Pushing image to Registry..."
    - docker push $REGISTRY_URL/$REGISTRY_USERNAME/$IMAGE_NAME:$TAG

# ---------------------------------------------------------------------------
# JOB 2: Template & Commit
# ---------------------------------------------------------------------------
update-manifest:
  stage: deploy
  image: line/kubectl-kustomize:latest
  needs:
    - build-and-push
  variables:
    CURRENT_USER: $[[ inputs.username ]]
  before_script:
    - apk add --no-cache git
  script:
    - export TAG="${CURRENT_USER}-$(echo $CI_COMMIT_SHA | cut -c1-8)"
    
    # 1. Clone the user-specific GitOps repo
    - git clone https://oauth2:${GITOPS_ACCESS_TOKEN}@${GITOPS_BASE_URL} gitops-repo
    - cd gitops-repo

    # 2. Update the root kustomization.yaml
    - kustomize edit set image myapp=${REGISTRY_USERNAME}/${IMAGE_NAME}:${TAG}
    - kustomize edit set nameprefix "${CURRENT_USER}-"

    # 3. Standard Git Push logic
    - git config --global user.email "yi.zhou@nutanix.com"
    - git config --global user.name "Zhou Yi"
    - |
      if [[ -n $(git status -s) ]]; then
        git add kustomization.yaml
        git commit -m "chore: update image to $TAG"
        git push origin main
      else
        echo "No changes detected in kustomization.yaml."
      fi