
---
apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: user01
  namespace: nkp-devops-lab
spec:
  cloneUrl: https://github.com/rhapsody008/devops-lab-gitops.git
  secret: git
  template:
    path: ./workloads/user01
    ref:
      branch: main

---
apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: user02
  namespace: nkp-devops-lab
spec:
  cloneUrl: https://github.com/rhapsody008/devops-lab-gitops.git
  secret: git
  template:
    path: ./workloads/user02
    ref:
      branch: main

---
apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: user03
  namespace: nkp-devops-lab
spec:
  cloneUrl: https://github.com/rhapsody008/devops-lab-gitops.git
  secret: git
  template:
    path: ./workloads/user03
    ref:
      branch: main

---
apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: user04
  namespace: nkp-devops-lab
spec:
  cloneUrl: https://github.com/rhapsody008/devops-lab-gitops.git
  secret: git
  template:
    path: ./workloads/user04
    ref:
      branch: main

---
apiVersion: dispatch.d2iq.io/v1alpha2
kind: GitopsRepository
metadata:
  name: user05
  namespace: nkp-devops-lab
spec:
  cloneUrl: https://github.com/rhapsody008/devops-lab-gitops.git
  secret: git
  template:
    path: ./workloads/user05
    ref:
      branch: main
